"""Remove to_account foreign key, add index

Revision ID: 0c7044495ed6
Revises: f6f1af96a8fb
Create Date: 2025-08-07 17:55:37.723340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c7044495ed6'
down_revision = 'f6f1af96a8fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_to_account_id'), ['to_account_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('transactions_to_account_id_fkey'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('transactions_to_account_id_fkey'), 'accounts', ['to_account_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_transactions_to_account_id'))

    # ### end Alembic commands ###
